# Generated by Django 5.2 on 2025-04-09 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_vehicles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicles',
            old_name='user_id',
            new_name='user',
        ),
    ]
