# Generated by Django 5.2 on 2025-04-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_user_id_vehicles_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='selected_vehicle',
            field=models.BooleanField(default=False),
        ),
    ]
