# Generated by Django 5.2 on 2025-04-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_vehicles_selected_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_google',
            field=models.BooleanField(default=False),
        ),
    ]
