# Generated by Django 5.2 on 2025-05-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_wallet_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
