# Generated by Django 5.2 on 2025-04-19 11:49

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0007_users_is_google'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('start_location_name', models.CharField(max_length=255)),
                ('destination_location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('destination_location_name', models.CharField(max_length=255)),
                ('pick_up_location', django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326)),
                ('drop_off_location', django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('route', django.contrib.gis.db.models.fields.LineStringField(geography=True, srid=4326)),
                ('route_distance', models.CharField(max_length=50)),
                ('passenger_count', models.PositiveIntegerField()),
                ('instant_booking', models.BooleanField(default=False)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='base.vehicles')),
            ],
        ),
        migrations.CreateModel(
            name='StopOvers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=255)),
                ('stop_location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('price', models.PositiveIntegerField()),
                ('position', models.PositiveIntegerField()),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stopover_prices', to='rides.ride')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['user'], name='rides_ride_user_id_50af28_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['date'], name='rides_ride_date_8d3f20_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['vehicle'], name='rides_ride_vehicle_5b5957_idx'),
        ),
    ]
