# Generated by Django 5.2 on 2025-04-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='duration',
            field=models.CharField(default='0 hr', max_length=25),
        ),
    ]
