# Generated by Django 5.2 on 2025-04-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_stopovers_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='stopovers',
            name='distance',
            field=models.CharField(default='0 km', max_length=25),
        ),
    ]
