# Generated by Django 5.2 on 2025-04-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_stopovers_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
