# Generated by Django 5.2 on 2025-04-22 11:04

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_ride_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('from_location', models.CharField(max_length=255)),
                ('from_short', models.CharField(max_length=10)),
                ('from_point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('to_location', models.CharField(max_length=255)),
                ('to_short', models.CharField(max_length=10)),
                ('to_point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('status', models.CharField(default='vacant', max_length=20)),
                ('booked_by', models.CharField(blank=True, max_length=255, null=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='rides.ride')),
            ],
            options={
                'verbose_name': 'Seat Segment',
                'verbose_name_plural': 'Seat Segments',
            },
        ),
    ]
