# Generated by Django 5.2 on 2025-04-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=models.CharField(choices=[('vacant', 'vacant'), ('booked', 'Booked')], default='vacant', max_length=20),
        ),
    ]
