# Generated by Django 5.2 on 2025-04-23 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0009_bookride'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='booked_by_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segments', to='rides.bookride'),
        ),
    ]
