# Generated by Django 5.2 on 2025-04-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0010_seat_booked_by_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookride',
            name='from_loc_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='bookride',
            name='to_loc_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
