# Generated by Django 5.2 on 2025-04-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0011_bookride_from_loc_name_bookride_to_loc_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookride',
            name='from_loc_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bookride',
            name='to_loc_name',
            field=models.CharField(max_length=255),
        ),
    ]
