# Generated by Django 5.2 on 2025-04-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0012_alter_bookride_from_loc_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookride',
            name='seat_segments',
            field=models.ManyToManyField(blank=True, related_name='held_by_bookings', to='rides.seat'),
        ),
        migrations.AlterField(
            model_name='bookride',
            name='booking_status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
