# Generated by Django 5.2 on 2025-05-07 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0015_ride_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookride',
            name='pickup_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
