# Generated by Django 5.2 on 2025-05-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0017_ride_is_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookride',
            name='book_otp',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
