# Generated by Django 5.2 on 2025-05-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0018_bookride_book_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookride',
            name='verified_otp',
            field=models.BooleanField(default=False),
        ),
    ]
