# Generated by Django 5.2 on 2025-05-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_book_payment_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='success',
            field=models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed'), ('incomplete', 'Incomplete'), ('pending', 'Pending')], default='incomplete', max_length=50),
        ),
    ]
