# Generated by Django 5.2 on 2025-05-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='wallet_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
